name: Build PyTorch 2.9.0 + CUDA 13.0 wheel

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The runner to use for the build"
        required: true
        type: string
        default: ubuntu-22.04
      python-version:
        description: "The Python version to use for the build"
        required: true
        type: string
        default: "3.12"
      cuda-version:
        description: "The CUDA version to use for the build"
        required: true
        type: string
        default: "13.0"
      torch-version:
        description: "The PyTorch version to use for the build"
        required: true
        type: string
        default: "2.9.0.dev"
      cxx11_abi:
        description: "Enable torch flag C++11 ABI (TRUE/FALSE)"
        required: true
        type: string
        default: "1"
      upload-to-release:
        description: "Upload wheel to this release"
        required: false
        type: boolean
        default: false
      release-version:
        description: "Upload wheel to this release"
        required: false
        type: string

jobs:
  build-pytorch29-cu130:
    uses: ./.github/workflows/pytorch2.9.0+cu130-linux-py312.yaml
    with:
      runs-on: ${{ inputs.runs-on }}
      python-version: ${{ inputs.python-version }}
      cuda-version: ${{ inputs.cuda-version }}
      torch-version: ${{ inputs.torch-version }}
      cxx11_abi: ${{ inputs.cxx11_abi }}
      upload-to-release: ${{ inputs.upload-to-release }}
      release-version: ${{ inputs.release-version }}
