name: Build Windows wheels and upload to GitHub Releases

on:
  create:
    tags:
      - "v*"

jobs:
  build_windows_wheels:
    name: Build wheels on Windows
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        torch-version: ["2.6.0", "2.7.0", "2.8.0"]
        python-version: ["3.12"]
        cuda-version: ["12.8"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CUDA Toolkit 12.8
        run: |
          choco install cuda --version=12.8 -y

      - name: Set CUDA paths
        run: |
          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8" >> $GITHUB_ENV
          echo "CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8" >> $GITHUB_ENV
          echo "PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin;$PATH" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel packaging ninja cmake

      - name: Clone flash-attention repo
        run: |
          git clone https://github.com/Dao-AILab/flash-attention.git flash-attn
          cd flash-attn
          git checkout v${{ github.ref_name }}

      - name: Build wheel
        working-directory: flash-attn
        run: |
          set FLASH_ATTENTION_FORCE_BUILD=TRUE
          python setup.py bdist_wheel --dist-dir=dist
          dir dist

      - name: Validate wheel build
        run: |
          if not exist flash-attn\dist\*.whl (
            echo "❌ Wheel build failed — dist folder or wheel not found."
            exit 1
          )

      - name: Upload wheel to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: flash-attn/dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
