name: pytorch2.9.0+cu130-linux-py312

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
      CUDA_VERSION: "13.0"
      TORCH_VERSION: "2.9.0.dev"
      CXX11_ABI: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Derive env
        id: derive
        run: |
          PYTAG="${PYTHON_VERSION/./}"              # 3.12 -> 312
          echo "PYTAG=$PYTAG" >> "$GITHUB_ENV"
          echo "TORCH_BASE=$(echo ${TORCH_VERSION} | awk -F. '{print $1"."$2}')" >> "$GITHUB_ENV"
          echo "CUDA_SHORT=$(echo ${CUDA_VERSION} | tr -d .)" >> "$GITHUB_ENV"
          echo "_GLIBCXX_USE_CXX11_ABI=${CXX11_ABI}" >> "$GITHUB_ENV"

      - name: Free disk space (Linux)
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL || true
          sudo apt-get purge -y -f qt5-doc qtbase5-doc || true
          sudo docker image prune -af || true

      - name: Set up swap (Linux)
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12

      - name: Install CUDA 13.0 toolkit
        id: cuda
        uses: Jimver/cuda-toolkit@v0.2.26
        with:
          cuda: "13.0"
          method: network

      - name: Validate PyTorch and CUDA
        run: |
          python -c "import torch; print('PyTorch:', torch.__version__); print('CUDA available:', torch.cuda.is_available()); print('CUDA version attr:', getattr(torch.version, 'cuda', None))"

      # Add your custom dependency installation and build commands below
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel ninja cmake

      - name: Build PyTorch wheel
        run: |
          git clone --recursive https://github.com/pytorch/pytorch
          cd pytorch
          git checkout v2.9.0
          git submodule sync
          git submodule update --init --recursive --jobs 0
          export USE_CUDA=1
          export USE_CUDNN=1
          export USE_MKLDNN=1
          python setup.py bdist_wheel

      - name: Upload built wheel
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-wheel
          path: pytorch/dist/*.whl
          
